<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ursa_bot">
    <xacro:include filename="materials.xacro"/>

    <!-- Degree-to-radian conversions -->
    <xacro:property name="degrees_45" value="0.785398163"/>
    <xacro:property name="degrees_90" value="1.57079633"/>
    <xacro:property name="degrees_180" value="3.14159265"/>

    <!-- Inertia Generator -->
    <xacro:macro name="default_inertial" params="mass">
        <inertial>
            <mass value="${mass}" />
            <inertia ixx="1.5" ixy="0.0" ixz="0.0" iyy="1.5" iyz="0.0" izz="1.5" />
        </inertial>
    </xacro:macro>

    <!-- Basic Geometry of Body -->
    <xacro:property name="body_length" value="1.91" />
    <xacro:property name="body_width" value="0.680618" />
    <xacro:property name="body_height" value="0.65" />
    <xacro:property name="body_mass" value="5.3"/>


    <!-- Front Wheel Properties -->
    <xacro:property name="front_wheel_width" value=".18" />
    <xacro:property name="front_wheel_diameter" value="0.5" />
    <xacro:property name="front_wheel_mass" value="2"/>

    <!-- Steering Link Properties -->
    <xacro:property name="steering_width" value="${front_wheel_width/4}" />
    <xacro:property name="steering_diameter" value="${front_wheel_diameter/5}" />
    <xacro:property name="steering_mass" value="2"/>

    <!-- Rear Wheel Properties -->
    <xacro:property name="rear_wheel_width" value="${front_wheel_width+steering_width}" />
    <xacro:property name="rear_wheel_diameter" value="0.5" />
    <xacro:property name="rear_wheel_mass" value="2"/>

    <!-- Base Link -->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="${body_mass}"/>
    </link>

    <!-- Steering Macro -->
    <xacro:macro name="steering_link" params="prefix reflect">

        <link name="${prefix}_steering_link">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="${degrees_90} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${steering_diameter}" length="${steering_width}"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${degrees_90} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${steering_diameter}" length="${steering_width}"/>
                </geometry>
            </collision>
            <xacro:default_inertial mass="${steering_mass}"/>
        </link>

        <joint name="${prefix}_steering_joint" type="revolute">
            <parent link="base_link"/>
            <child link="${prefix}_steering_link"/>
            <axis xyz="0.0 0.0 0.1"/>
            <origin xyz="${(body_length / 2)- 0.1} ${(body_width / 2 + steering_width / 2) * reflect} ${-(body_height/2) + 0.1}" rpy="0.0 0.0 0.0"/>
            <limit lower="-0.30" upper="0.30" effort="100.00" velocity="100.00"/>
        </joint>

        <!-- The Transmission -->
        <transmission name="${prefix}_steering_link_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${prefix}_steering_joint">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            </joint>
            <actuator name="${prefix}_steering_link_motor">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

    </xacro:macro>

    <!-- Front Wheel Macro -->
    <xacro:macro name="front_wheel_link" params="prefix reflect">

        <link name="${prefix}_front_wheel">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="${degrees_90} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${front_wheel_diameter/2}" length="${front_wheel_width}"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${degrees_90} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${front_wheel_diameter/2}" length="${front_wheel_width}"/>
                </geometry>
            </collision>
            <xacro:default_inertial mass="${front_wheel_mass}"/>
        </link>

        <joint name="${prefix}_front_axle" type="continuous">
            <parent link="${prefix}_steering_link"/>
            <child link="${prefix}_front_wheel"/>
            <axis xyz="0.0 0.1 0.0"/>
            <origin xyz="0 ${(front_wheel_width/2 + steering_width/2) * reflect} 0"/>
        </joint>

        <!-- The Transmission -->
        <transmission name="${prefix}_front_wheel_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${prefix}_front_axle">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="${prefix}_front_wheel_motor">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

    </xacro:macro>

    <!-- Rear Wheel Macro -->
    <xacro:macro name="rear_wheel_link" params="prefix reflect">

        <link name="${prefix}_rear_wheel">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="${degrees_90} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${rear_wheel_diameter/2}" length="${rear_wheel_width}"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${degrees_90} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${rear_wheel_diameter/2}" length="${rear_wheel_width}"/>
                </geometry>
            </collision>
            <xacro:default_inertial mass="${rear_wheel_mass}"/>
        </link>

        <joint name="${prefix}_rear_axle" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_rear_wheel"/>
            <axis xyz="0.0 0.1 0.0"/>
            <origin xyz="${-(body_length/2) + 0.1} ${(rear_wheel_width/2 + body_width/2) * reflect} ${-(body_height/2) + 0.1}"/>
        </joint>

        <!-- The Transmission -->
        <transmission name="${prefix}_rear_wheel_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${prefix}_rear_axle">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="${prefix}_rear_wheel_motor">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

    </xacro:macro>

    <xacro:steering_link prefix="left" reflect="1" />
    <xacro:steering_link prefix="right" reflect="-1" />

    <xacro:front_wheel_link prefix="left" reflect="1" />
    <xacro:front_wheel_link prefix="right" reflect="-1" />

    <xacro:rear_wheel_link prefix="left" reflect="1" />
    <xacro:rear_wheel_link prefix="right" reflect="-1" />

    <link name="front_steer">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${front_wheel_diameter/2}" length="${front_wheel_width/2}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${front_wheel_diameter/2}" length="${front_wheel_width/2}"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="${front_wheel_mass}"/>
    </link>
    <link name="rear_wheel">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="${degrees_90} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${front_wheel_diameter/2}" length="${front_wheel_width/2}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="${degrees_90} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${front_wheel_diameter/2}" length="${front_wheel_width/2}"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="${front_wheel_mass}"/>
    </link>

    <joint name="front_steer_joint" type="revolute">
        <parent link="base_link"/>
        <child link="front_steer"/>
        <axis xyz="0.0 0.0 0.1"/>
        <origin xyz="0.7 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <limit lower="-0.50" upper="0.50" effort="1000" velocity="3"/>
    </joint>

    <joint name="rear_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="rear_wheel"/>

        <axis xyz="0.0 1.0 0.0"/>
        <origin xyz="-0.70 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <limit effort="1000.0" velocity="3.0"/>
    </joint>

    <transmission name="front_steer_joint_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="front_steer_joint">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="front_steer_joint_motor">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="rear_wheel_joint_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="rear_wheel_joint">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="rear_wheel_joint_motor">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <!-- Gazebo plugin for ROS Control -->
    <gazebo>
       <plugin name="gazebo_ros_ackermann_drive" filename="libgazebo_ros_ackermann_drive.so">

  <ros>
    <namespace>/</namespace>
    <remapping>cmd_vel:=cmd_vel</remapping>
    <remapping>odom:=odom</remapping>
    <remapping>distance:=distance</remapping>
  </ros>

  <update_rate>100.0</update_rate>

  <!-- wheels -->
  <front_left_joint>left_front_axle</front_left_joint>
  <front_right_joint>right_front_axle</front_right_joint>
  <rear_left_joint>left_rear_axle</rear_left_joint>
  <rear_right_joint>right_rear_axle</rear_right_joint>
  <left_steering_joint>left_steering_joint</left_steering_joint>
  <right_steering_joint>right_steering_joint</right_steering_joint>
  <steering_wheel_joint>front_steer_joint</steering_wheel_joint>

  <!-- Max absolute steer angle for tyre in radians-->
  <!-- Any cmd_vel angular z greater than this would be capped -->
  <max_steer>0.6458</max_steer>

  <!-- Max absolute steering angle of steering wheel -->
  <max_steering_angle>7.85</max_steering_angle>

  <!-- Max absolute linear speed in m/s -->
  <max_speed>20</max_speed>

  <!-- PID tuning -->
  <left_steering_pid_gain>1500 0 1</left_steering_pid_gain>
  <left_steering_i_range>0 0</left_steering_i_range>
  <right_steering_pid_gain>1500 0 1</right_steering_pid_gain>
  <right_steering_i_range>0 0</right_steering_i_range>
  <linear_velocity_pid_gain>1000 0 1</linear_velocity_pid_gain>
  <linear_velocity_i_range>0 0</linear_velocity_i_range>

  <!-- output -->
  <publish_odom>true</publish_odom>
  <publish_odom_tf>true</publish_odom_tf>
  <publish_wheel_tf>true</publish_wheel_tf>
  <publish_distance>true</publish_distance>

  <odometry_frame>odom</odometry_frame>
  <robot_base_frame>base_link</robot_base_frame>

</plugin>
    </gazebo>
</robot>